"""
Stores original invoice images so they're retained alongside the extracted
data (and so auto-backup has something meaningful to back up).

Uses Supabase Storage when SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are set
(needed for production - Render's filesystem is ephemeral and wipes local
files on every restart/redeploy). Falls back to local disk otherwise, so
local development without a Supabase project still works.
"""
import uuid
from pathlib import Path

from . import supabase_client

LOCAL_UPLOADS_DIR = Path(__file__).resolve().parent.parent / "uploads" / "invoices"
LOCAL_UPLOADS_DIR.mkdir(parents=True, exist_ok=True)

_logo_cache = {"url": None, "bytes": None}


def save_invoice_image(file_bytes: bytes, original_filename: str) -> str:
    ext = Path(original_filename).suffix or ".jpg"
    name = f"{uuid.uuid4()}{ext}"

    if supabase_client.is_configured():
        content_type = _guess_content_type(ext)
        return supabase_client.upload_bytes(name, file_bytes, content_type)

    # Local dev fallback
    path = LOCAL_UPLOADS_DIR / name
    with open(path, "wb") as f:
        f.write(file_bytes)
    return f"/files/invoices/{name}"


def save_company_logo(file_bytes: bytes, original_filename: str, company_id: str) -> str:
    """Fixed filename PER COMPANY, so re-uploading a logo replaces that
    company's old one in place (no orphaned files with every change) - but
    critically, the company_id is part of the filename specifically so two
    different companies' logos can never collide/overwrite each other. An
    earlier version of this used a single shared filename for everyone,
    which would have let one company's logo upload silently overwrite
    another's."""
    ext = Path(original_filename).suffix or ".png"
    name = f"company_logo_{company_id}{ext}"

    if supabase_client.is_configured():
        content_type = _guess_content_type(ext)
        url = supabase_client.upload_bytes(name, file_bytes, content_type)
    else:
        path = LOCAL_UPLOADS_DIR / name
        with open(path, "wb") as f:
            f.write(file_bytes)
        url = f"/files/invoices/{name}"

    # We already have the fresh bytes right here - update the cache directly
    # instead of making every subsequent bill/PDF generation re-fetch the
    # logo over the network. This also correctly invalidates any previous
    # cached logo, which a plain URL-keyed cache wouldn't do on its own
    # (save_company_logo reuses the same filename/URL every time it's
    # re-uploaded, precisely so replacing a logo doesn't leave orphans).
    _logo_cache["url"] = url
    _logo_cache["bytes"] = file_bytes
    return url


def get_cached_logo_bytes(url: str) -> bytes | None:
    """Cached accessor specifically for the company logo, which is read on
    every single PDF export and bill generation but changes only rarely.
    Avoids a real network round-trip to Supabase Storage on each call."""
    if _logo_cache["url"] == url and _logo_cache["bytes"] is not None:
        return _logo_cache["bytes"]
    data = read_image_bytes(url)
    if data is not None:
        _logo_cache["url"] = url
        _logo_cache["bytes"] = data
    return data


def save_generated_bill(file_bytes: bytes) -> str:
    """Stores a bill image generated by the app itself (see bill_generator.py)."""
    name = f"bill_{uuid.uuid4()}.jpg"

    if supabase_client.is_configured():
        return supabase_client.upload_bytes(name, file_bytes, "image/jpeg")

    path = LOCAL_UPLOADS_DIR / name
    with open(path, "wb") as f:
        f.write(file_bytes)
    return f"/files/invoices/{name}"


def read_image_bytes(url_or_path: str) -> bytes | None:
    """Reads back an image previously saved via this module, regardless of
    whether it lives in Supabase Storage (full URL) or local disk (relative path).
    Used by PDF generation to embed the logo."""
    import httpx

    if url_or_path.startswith("http://") or url_or_path.startswith("https://"):
        try:
            with httpx.Client(timeout=15.0) as client:
                resp = client.get(url_or_path)
            return resp.content if resp.status_code == 200 else None
        except Exception:
            return None

    # Local disk mode: URLs look like "/files/invoices/xxx.jpg" (served via the
    # /files static mount in main.py), which maps to the actual uploads/ dir.
    relative = url_or_path.lstrip("/")
    if relative.startswith("files/"):
        relative = "uploads/" + relative[len("files/"):]
    local_path = Path(__file__).resolve().parent.parent / relative
    if local_path.exists():
        return local_path.read_bytes()
    return None


def _guess_content_type(ext: str) -> str:
    return {
        ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".png": "image/png", ".webp": "image/webp",
    }.get(ext.lower(), "application/octet-stream")
