"""
Stores original invoice images so they're retained alongside the extracted
data (and so auto-backup has something meaningful to back up).

Uses Supabase Storage when SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY are set
(needed for production - Render's filesystem is ephemeral and wipes local
files on every restart/redeploy). Falls back to local disk otherwise, so
local development without a Supabase project still works.
"""
import uuid
from pathlib import Path

from . import supabase_client

LOCAL_UPLOADS_DIR = Path(__file__).resolve().parent.parent / "uploads" / "invoices"
LOCAL_UPLOADS_DIR.mkdir(parents=True, exist_ok=True)


def save_invoice_image(file_bytes: bytes, original_filename: str) -> str:
    ext = Path(original_filename).suffix or ".jpg"
    name = f"{uuid.uuid4()}{ext}"

    if supabase_client.is_configured():
        content_type = _guess_content_type(ext)
        return supabase_client.upload_bytes(name, file_bytes, content_type)

    # Local dev fallback
    path = LOCAL_UPLOADS_DIR / name
    with open(path, "wb") as f:
        f.write(file_bytes)
    return f"/files/invoices/{name}"


def save_company_logo(file_bytes: bytes, original_filename: str) -> str:
    """Always uses a fixed filename so re-uploading a logo replaces the old one
    in place, rather than accumulating orphaned files with every change."""
    ext = Path(original_filename).suffix or ".png"
    name = f"company_logo{ext}"

    if supabase_client.is_configured():
        content_type = _guess_content_type(ext)
        return supabase_client.upload_bytes(name, file_bytes, content_type)

    path = LOCAL_UPLOADS_DIR / name
    with open(path, "wb") as f:
        f.write(file_bytes)
    return f"/files/invoices/{name}"


def save_generated_bill(file_bytes: bytes) -> str:
    """Stores a bill image generated by the app itself (see bill_generator.py)."""
    name = f"bill_{uuid.uuid4()}.jpg"

    if supabase_client.is_configured():
        return supabase_client.upload_bytes(name, file_bytes, "image/jpeg")

    path = LOCAL_UPLOADS_DIR / name
    with open(path, "wb") as f:
        f.write(file_bytes)
    return f"/files/invoices/{name}"


def read_image_bytes(url_or_path: str) -> bytes | None:
    """Reads back an image previously saved via this module, regardless of
    whether it lives in Supabase Storage (full URL) or local disk (relative path).
    Used by PDF generation to embed the logo."""
    import httpx

    if url_or_path.startswith("http://") or url_or_path.startswith("https://"):
        try:
            with httpx.Client(timeout=15.0) as client:
                resp = client.get(url_or_path)
            return resp.content if resp.status_code == 200 else None
        except Exception:
            return None

    # Local disk mode: URLs look like "/files/invoices/xxx.jpg" (served via the
    # /files static mount in main.py), which maps to the actual uploads/ dir.
    relative = url_or_path.lstrip("/")
    if relative.startswith("files/"):
        relative = "uploads/" + relative[len("files/"):]
    local_path = Path(__file__).resolve().parent.parent / relative
    if local_path.exists():
        return local_path.read_bytes()
    return None


def _guess_content_type(ext: str) -> str:
    return {
        ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".png": "image/png", ".webp": "image/webp",
    }.get(ext.lower(), "application/octet-stream")
